apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: mynamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecrete
              key: mongo-root-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecrete
              key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mynamespace
spec:
  selector:
    app: monogodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

              
